---
# INPUT
account_name: sandbox1
account_email: sandbox1@opentlc.com
account_user: student
#account_destination_ou
#account_id

aws_master_profile: gpe-gucore
aws_region: us-east-1

account_profile: "{{ account_name }}"
aws_role_name: OrganizationAccountAccessRole

subdomain_base: .opentlc.com
output_dir: '.'
