---
- name: Copy IAM template to output_dir
  copy:
    dest: "{{ output_dir }}/CF-IAM.json"
    src: files/CF-IAM.json

- name: Create IAM role using Cloudformation
  cloudformation:
    profile: "{{ account_profile }}"
    template: "{{ output_dir }}/CF-IAM.json"
    region: "{{ aws_region }}"
    stack_name: roles
