---
- name: Login kerberos
  command: >-
    kinit {{ kerberos_user }}
  args:
    stdin: "{{ kerberos_password }}"

- name: Add NS records to IPA
  command: >-
    ipa dnsrecord-add {{ ipa_domain }}. {{ account_name }} --ns-rec={{ _z }}.
  loop: "{{ ns_records }}"
  loop_control:
    loop_var: _z
