---
- name: Login kerberos
  command: >-
    kinit {{ kerberos_user }}
  args:
    stdin: "{{ kerberos_password }}"

- name: Fetch all NS records for this sandbox
  shell: >-
    ipa dnsrecord-find {{ ipa_domain }}. {{ account_name }} --raw
    | awk '/idnsname: {{ account_name }}$/{flag=1;next}/idnsname:/{flag=0}flag'
    | grep nsrecord:
    | perl -pe 's/ *nsrecord: *//;s/\.$//'
  register: _recordfind

- name: Delete all NS records that are not needed anymore
  command: >-
    ipa dnsrecord-del {{ ipa_domain }}. {{ account_name }} --ns-rec={{ _z }}.
  loop_control:
    loop_var: _z
  loop: "{{ _recordfind.stdout.split('\n') | difference(ns_records) }}"

- name: Add NS records to IPA
  command: >-
    ipa dnsrecord-add {{ ipa_domain }}. {{ account_name }} --ns-rec={{ _z }}.
  loop: "{{ ns_records }}"
  loop_control:
    loop_var: _z
  register: _ipacommand
  failed_when:
    - _ipacommand.rc != 0
    - '"ERROR: no modifications to be performed" not in _ipacommand.stderr'
  changed_when: >-
    "ERROR: no modifications to be performed"
    not in _ipacommand.stderr
