---
- name: Create output_dir
  file:
    path: "{{ output_dir }}"
    state: directory

- include_tasks: test_ipa.yml
  when:
    - kerberos_user is defined
    - kerberos_password is defined

- import_tasks: account.yml
- import_tasks: profile.yml
- import_tasks: iam.yml

- include_tasks: ou.yml
  when: account_destination_ou is defined

- import_tasks: user.yml
- import_tasks: route53.yml
- include_tasks: ipa.yml
  when:
    - kerberos_user is defined
    - kerberos_password is defined
