---
- import_tasks: pre_checks.yml
- import_tasks: account.yml
- import_tasks: profile.yml
- import_tasks: iam.yml
- import_tasks: alias.yml
- include_tasks: ou.yml
  when: account_destination_ou is defined
- import_tasks: user.yml
- include_tasks: reset.yml
  when: action == 'RESET'
- import_tasks: route53.yml
- import_tasks: keypair.yml
- include_tasks: ipa.yml
  when:
    - kerberos_user is defined
    - kerberos_password is defined
