---
- name: Set account arn
  set_fact:
    account_arn: "arn:aws:iam::{{ account_id }}:role/{{ aws_role_name }}"

- debug:
    var: account_arn

- name: Creating a new AWS profile for the new account
  shell: |-
    aws --profile {{ account_profile }} configure set region {{ aws_region }}
    aws --profile {{ account_profile }} configure set role_arn {{ account_arn }}
    aws --profile {{ account_profile }} configure set source_profile {{ aws_master_profile }}
