---
- name: Download aws-nuke
  become: yes
  get_url:
    url: "{{ aws_nuke_binary_url }}"
    dest: /usr/bin/aws-nuke
    mode: 755
    owner: root
    group: root

- name: Generate config file for aws-nuke
  template:
    src: "{{ role_path }}/templates/nuke-config.yml.j2"
    dest: "{{ output_dir }}/{{ account_name }}_nuke-config.yml"

- name: Run aws-nuke on in the sandbox account profile
  command: >-
    aws-nuke --profile {{ account_name }}
    -c "{{ output_dir }}/{{ account_name }}_nuke-config.yml"
    --no-dry-run
    --force
  args:
    stdin: "{{ account_name }}{{ alias_suffix }}"
  register: _awsnuke

- debug:
    var: _awsnuke

- name: Create the public zone
  environment:
    AWS_PROFILE: "{{ account_profile }}"
  route53_zone:
    zone: "{{ account_name }}{{subdomain_base}}"
  register: _route53zone

- include_tasks: clean_zone.yml
  vars:
    _hostedzoneid: "{{ _route53zone.zone_id }}"
    aws_public_zone: "{{ account_name }}{{subdomain_base}}."

    
