---
- environment:
    AWS_PROFILE: "{{ account_profile }}"
  block:
    - name: Create the public zone
      route53_zone:
        zone: "{{ account_name }}{{subdomain_base}}"
      register: _route53zone

    - name: Grab facts about the zone
      route53_facts:
        query: hosted_zone
        hosted_zone_method: details
        hosted_zone_id: "{{ _route53zone.zone_id }}"
      register: _route53facts

    - name: Save NS records
      set_fact:
        ns_records: "{{ _route53facts.DelegationSet.NameServers }}"

    - name: Generate commands to del NS records to IPA
      copy:
        content: |-
          ipa dnsrecord-del opentlc.com. {{ account_name }}
        dest: "{{ output_dir }}/ipa_del_{{ account_name }}.sh"

    - name: Add HostedZoneId to the report
      lineinfile:
        path: "{{ output_dir }}/{{ account_name }}_report.txt"
        line: "HostedZoneId: {{ _route53zone.zone_id }}"

    - name: Add Zone name to the report
      lineinfile:
        path: "{{ output_dir }}/{{ account_name }}_report.txt"
        line: "Zone: {{ account_name }}{{subdomain_base}}"



