---
- name: Create the public zone
  route53_zone:
    zone: "{{ account_name }}{{subdomain_base}}"
  register: _route53zone

- name: Grab facts about the zone
  route53_facts:
    query: hosted_zone
    hosted_zone_method: details
    hosted_zone_id: "{{ _route53zone.zone_id }}"
  register: _route53facts

- name: Save NS records
  set_fact:
    ns_records: "{{ _route53facts.DelegationSet.NameServers }}"

- name: Save NS records to file
  copy:
    content: |-
      {% for _z in ns_records %}
      {{ account_name }} {{ _z }}
      {% endfor %}
    dest: "{{ output_dir }}/{{ account_name }}.nsrecords.txt"
