---
- name: Ensure ipa is installed
  shell: command -v ipa
  register: _commandipa
  failed_when: false
  changed_when: false

- fail:
    msg: IPA client is not installed.
  when: _commandipa.rc != 0

- name: Login kerberos
  command: >-
    kinit {{ kerberos_user }}
  args:
    stdin: "{{ kerberos_password }}"
